### ISSUE TITLE
Broken for 3.4.1

### ISSUE THREAD

**Issue by YuanUS** [Nevcairiel/Quester#3]
How are u, could u fix error for 3.4.1? Thank u so much.

89x Interface/AddOns/Quester/Quester.lua:763: attempt to call global 'GetGossipAvailableQuests' (a nil value)
[string "@Interface/AddOns/Quester/Quester.lua"]:763: in function `?'
[string "@Interface/AddOns/Quester/Quester.lua"]:424: in function `HandleEvent'
[string "@Interface/AddOns/Quester/Quester.lua"]:407: in function <Interface/AddOns/Quester/Quester.lua:407>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 QUEST_GREETING = <function> defined @Interface/AddOns/Quester/Quester.lua:771
 SetSinkStorage = <function> defined @Interface/AddOns/Prat-3.0_Libraries/LibSink-2.0/LibSink-2.0.lua:829
 EnableModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "Quester"
 IterateEmbeds = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHook = <function> defined @Interface/AddOns/Mapster/Libs/AceHook-3.0/AceHook-3.0.lua:335
 RawHookScript = <function> defined @Interface/AddOns/Mapster/Libs/AceHook-3.0/AceHook-3.0.lua:394
 HandleEvent = <function> defined @Interface/AddOns/Quester/Quester.lua:422
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetSinkAce3OptionsDataTable = <function> defined @Interface/AddOns/Prat-3.0_Libraries/LibSink-2.0/LibSink-2.0.lua:672
 ToggleTrackerMovable = <function> defined @Interface/AddOns/Quester/Quester.lua:460
 QUEST_COMPLETE = <function> defined @Interface/AddOns/Quester/Quester.lua:915
 defaultModuleState = true
 IsEnabled = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 GetArgs = <function> defined @Interface/AddOns/Atlas/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 RegisterSink = <function> defined @Interface/AddOns/Prat-3.0_Libraries/LibSink-2.0/LibSink-2.0.lua:791
 hooks = <table> {
 }
 db = <table> {
 }
 GOSSIP_SHOW = <function> defined @Interface/AddOns/Quester/Quester.lua:760
 eventFrame = QuesterEventFrame {
 }
 SetEnabledState = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/Mapster/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 RestoreTrackerPosition = <function> defined @Interface/AddOns/Quester/Quester.lua:410
 RegisterEvent = <function> defined @Interface/AddOns/Quester/Quester.lua:417
 IterateModules = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 RawHook = <function> defined @Interface/AddOns/Mapster/Libs/AceHook-3.0/AceHook-3.0.lua:312
 OnInitialize = <function> defined @Interface/AddOns/Quester/Quester.lua:392
 RegisterChatCommand = <function> defined @Interface/AddOns/Atlas/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 GetModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface/AddOns/Atlas/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 GetName = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "Quester"
 orderedModules = <table> {
 }
 GetSinkAce2OptionsDataTable = <function> defined @Interface/AddOns/Prat-3.0_Libraries/LibSink-2.0/LibSink-2.0.lua:608
 Disable = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 EnvironmentProxy = <function> defined @Interface/AddOns/Quester/Quester.lua:850
 Unhook = <function> defined @Interface/AddOns/Mapster/Libs/AceHook-3.0/AceHook-3.0.lua:417
 Print = <function> defined @Interface/AddOns/Atlas/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 Enable = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 IsModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 NewModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 SetDefaultModuleState = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 QUEST_LOG_UPDATE = <function> defined @Interface/AddOns/Quester/Quester.lua:663
 SetRewardHighlight = <function> defined @Interface/AddOns/Quester/Quester.lua:904
 PLAYER_LEAVING_WORLD = <function> defined @Interface/AddOns/Quester/Quester.lua:580
 SecureHookScript = <function> defined @

**Comment by loeppenberg** [comment]
until this is fixed by the author for wrath, you can make these changes manually that he did for the retail version. works fine for me in wrath classic:

https://github.com/Nevcairiel/Quester/commit/bcc141c140d8a337f18247c25bce489f2b6745ab#diff-b61b3377ec0ce33e15ae5fd7acf8b659640d8a66b2a90e890f2775d53a19512b

**Comment by Nevcairiel** [comment]
Quester was never designed to work on Classic.
